// Seed products — used as fallback when Supabase is not yet configured
import { Product } from "@/types";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "seed-1",
    slug: "eucalyptus-face-scrub",
    name: "Eucalyptus Face Scrub",
    tagline: "Clarifying & Cooling",
    description:
      "Breathe deeply and let your skin reset. Our Eucalyptus Face Scrub is a mindfully crafted blend of pure eucalyptus essential oil, fine sugar exfoliants, and soothing aloe vera — designed to clear away impurities while leaving your skin feeling refreshed and alive. Each bar is cold-processed and cured for six weeks to ensure a rich, creamy lather that truly nourishes. Free from sulfates, synthetic fragrances, and preservatives.",
    price: 23.0,
    stock_qty: 12,
    is_active: true,
    badge: "Bestseller",
    category: ["Face & Body Scrubs"],
    ritual_tags: ["Energizing", "Detoxifying"],
    ingredients:
      "Aqua, Cocos Nucifera (Coconut) Oil, Eucalyptus Globulus Leaf Oil, Aloe Barbadensis Leaf Juice, Sucrose, Kaolin Clay, Glycerin, Citric Acid.",
    image_urls: ["/images/products/product-eucalyptus.jpg"],
    is_featured: true,
    sort_order: 1,
    recommended_ids: ["seed-2", "seed-3"],
    shapes: ["Square", "Rectangle"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-3",
    slug: "cocoa-powder-soap",
    name: "Cocoa Powder Soap",
    tagline: "Rich Antioxidants",
    description:
      "Warm. Grounding. Utterly indulgent. Our Cocoa Powder Soap wraps your skin in a velvety lather rich with raw cacao, organic oat milk, and a whisper of vanilla. Cocoa is naturally loaded with antioxidants that help fight environmental stressors and support skin elasticity. This is your daily ritual reimagined — skin care that smells like self-love.",
    price: 25.0,
    stock_qty: 9,
    is_active: true,
    badge: null,
    category: ["Botanical Bars"],
    ritual_tags: ["Soothing", "Unscented"],
    ingredients:
      "Saponified Cocos Nucifera (Coconut) Oil, Theobroma Cacao (Cocoa) Powder, Avena Sativa (Oat) Milk, Vanilla Planifolia Extract, Ricinus Communis (Castor) Oil, Butyrospermum Parkii (Shea) Butter.",
    image_urls: ["/images/products/product-cocoa.jpg"],
    is_featured: true,
    sort_order: 2,
    recommended_ids: ["seed-1", "seed-2"],
    shapes: ["Rectangle"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-2",
    slug: "aloe-vera-soap",
    name: "Aloe Vera Soap",
    tagline: "Hydrating & Gentle",
    description:
      "Gentle enough for the most sensitive skin, powerful enough to make a real difference. Our Aloe Vera Soap is built on a foundation of fresh aloe vera juice, skin-loving olive oil, and nourishing shea butter. Aloe's natural enzymes and polysaccharides help restore skin's moisture barrier while calendula extract provides a soft, anti-inflammatory touch. Every wash feels like a quiet act of kindness toward your body.",
    price: 25.0,
    stock_qty: 18,
    is_active: true,
    badge: null,
    category: ["Botanical Bars", "Naturals"],
    ritual_tags: ["Soothing"],
    ingredients:
      "Saponified Olea Europaea (Olive) Oil, Cocos Nucifera (Coconut) Oil, Aloe Barbadensis Leaf Juice, Butyrospermum Parkii (Shea) Butter, Calendula Officinalis Flower Extract.",
    image_urls: ["/images/products/product-aloe.jpg"],
    is_featured: true,
    sort_order: 3,
    recommended_ids: ["seed-1", "seed-5"],
    shapes: ["Rectangle", "Square"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-4",
    slug: "spiral-pop-poe",
    name: "Spiral Pop Poe",
    tagline: "Playful & Nourishing",
    description:
      "Bold, vibrant, and full of joy — Spiral Pop Poe is for those who believe self-care should feel celebratory. This eye-catching circular bar swirls together a skin-loving blend of coconut and palm oils, scented with a bright, uplifting fragrance. It lathers beautifully, leaves skin soft and smooth, and brings a pop of color to any bathroom. A wonderful gift for yourself or someone you love.",
    price: 25.0,
    stock_qty: 7,
    is_active: true,
    badge: "New",
    category: ["Botanical Bars"],
    ritual_tags: ["Energizing"],
    ingredients:
      "Saponified Cocos Nucifera (Coconut) Oil, Elaeis Guineensis (Palm) Oil, Butyrospermum Parkii (Shea) Butter, Fragrance (Skin-Safe), Mica (Colorant), Ricinus Communis (Castor) Oil.",
    image_urls: [
      "https://images.unsplash.com/photo-1607006483120-00971b569238?auto=format&fit=crop&q=80&w=800",
    ],
    is_featured: true,
    sort_order: 4,
    recommended_ids: ["seed-2", "seed-5"],
    shapes: ["Circle"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-5",
    slug: "lavender-wild-oat",
    name: "Lavender & Wild Oat",
    tagline: "Calming Sleep Ritual",
    description:
      "Some rituals are worth protecting. Light a candle, draw a warm bath, and reach for our Lavender & Wild Oat bar. French lavender essential oil works alongside colloidal wild oat extract and chamomile to quiet the nervous system and nourish stressed or reactive skin. This is our most beloved wind-down bar — crafted for those who understand that rest is not a luxury, it is medicine.",
    price: 25.0,
    stock_qty: 5,
    is_active: true,
    badge: "Limited",
    category: ["Naturals", "Botanical Bars"],
    ritual_tags: ["Soothing"],
    ingredients:
      "Saponified Olea Europaea (Olive) Oil, Lavandula Angustifolia (Lavender) Essential Oil, Avena Sativa (Wild Oat) Extract, Anthemis Nobilis (Chamomile) Flower Extract, Butyrospermum Parkii (Shea) Butter.",
    image_urls: [
      "https://images.unsplash.com/photo-1546552356-3fae876a61ca?auto=format&fit=crop&q=80&w=800",
    ],
    is_featured: false,
    sort_order: 5,
    recommended_ids: ["seed-2", "seed-3"],
    shapes: ["Square", "Rectangle"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-6",
    slug: "activated-charcoal-detox",
    name: "Activated Charcoal Detox",
    tagline: "Deep Pore Cleansing",
    description:
      "Give your skin the deep reset it deserves. Activated charcoal works like a magnet, drawing out toxins, excess sebum, and impurities from deep within pores. We've paired it with tea tree essential oil — nature's antiseptic — and bentonite clay to deliver a thorough yet balanced detox without stripping your skin's natural moisture. Ideal after long days, heavy workouts, or whenever your skin needs to breathe again.",
    price: 25.0,
    stock_qty: 14,
    is_active: true,
    badge: null,
    category: ["Face & Body Scrubs", "Naturals"],
    ritual_tags: ["Detoxifying"],
    ingredients:
      "Saponified Cocos Nucifera (Coconut) Oil, Activated Charcoal, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Bentonite Clay, Ricinus Communis (Castor) Oil.",
    image_urls: [
      "https://images.unsplash.com/photo-1626015523023-e63065b2f6b8?auto=format&fit=crop&q=80&w=800",
    ],
    is_featured: false,
    sort_order: 6,
    recommended_ids: ["seed-1", "seed-3"],
    shapes: ["Square", "Circle"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
